name: Pull Request
on:
  push:
    branches: 
      - "feature/*"

jobs:
  pull-request:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: pull-request
      uses: repo-sync/pull-request@v2.0.1
      with:
        pr_title: "Pulling ${{ github.ref }} into master"
        # Pull request body
        pr_body: ":crown: *Automated pull request for review*"
        # Pull request labels, comma-separated list (no spaces)
        pr_label: "auto-pr"
        # GitHub token secret
        github_token: ${{ secrets.GITHUB_TOKEN }}
